name: Decisions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25071
title: Gourmet Pizzas - Homemade Gourmet Fudges
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#1d1a1f'
    - '#c7baa8'
    - '#fe022d'
    - '#71685f'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.6750292899087071
purpose: []
